name: Build Docker Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/wxf190/kaiyuan:2026 .

      - name: Push image
        run: |
          docker push ghcr.io/wxf190/kaiyuan:2026
